import type { PermissionAction, RoleName } from "@/lib/types";

export const rolePermissions: Record<RoleName, PermissionAction[]> = {
  Owner: [
    "workspace.manage",
    "admin.manage",
    "users.invite",
    "users.remove",
    "roles.manage",
    "projects.create",
    "projects.update",
    "content.create",
    "content.publish",
    "content.organize",
    "library.manage",
    "keywords.manage",
    "personas.manage",
    "ai.generate",
    "ai.manage",
    "media.generate",
    "media.manage",
    "billing.manage",
    "export_video",
    "download_package",
    "mark_as_published",
    "edit_metadata",
    "upload_asset",
    "delete_asset",
    "edit_asset",
    "favorite_asset",
    "create_collection",
    "import_external_asset",
    "view_templates",
    "create_template",
    "edit_template",
    "delete_template",
    "use_template",
    "manage_template_packs",
    "audit.read"
  ],
  Admin: [
    "workspace.manage",
    "admin.manage",
    "users.invite",
    "users.remove",
    "projects.create",
    "projects.update",
    "content.create",
    "content.publish",
    "content.organize",
    "library.manage",
    "keywords.manage",
    "personas.manage",
    "ai.generate",
    "ai.manage",
    "media.generate",
    "media.manage",
    "export_video",
    "download_package",
    "mark_as_published",
    "edit_metadata",
    "upload_asset",
    "delete_asset",
    "edit_asset",
    "favorite_asset",
    "create_collection",
    "import_external_asset",
    "view_templates",
    "create_template",
    "edit_template",
    "delete_template",
    "use_template",
    "manage_template_packs",
    "audit.read"
  ],
  Manager: [
    "users.invite",
    "projects.create",
    "projects.update",
    "content.create",
    "content.publish",
    "content.organize",
    "keywords.manage",
    "personas.manage",
    "ai.generate",
    "media.generate",
    "export_video",
    "download_package",
    "mark_as_published",
    "edit_metadata",
    "upload_asset",
    "edit_asset",
    "favorite_asset",
    "create_collection",
    "import_external_asset",
    "view_templates",
    "create_template",
    "edit_template",
    "use_template",
    "audit.read"
  ],
  Editor: ["projects.update", "content.create", "content.organize", "library.manage", "keywords.manage", "personas.manage", "ai.generate", "media.generate", "export_video", "download_package", "edit_metadata", "upload_asset", "edit_asset", "favorite_asset", "view_templates", "use_template"],
  Viewer: ["audit.read"]
};

export function can(role: RoleName, permission: PermissionAction) {
  return rolePermissions[role].includes(permission);
}
